var songs = [
    {
        id: 1,
        name: 'Future - Mask Off',
        singer: 'Ablaikan Remix',
        path: './assets./music/song1.mp3',
        image: './assets./img/song1.jpg',
    },
    {
        id: 2,
        name: 'Temple (Kain Remix)',
        singer: 'Liu & Zerky',
        path: './assets/music/song2.mp3',
        image: './assets./img/song2.jpg',
    },
    {
        id: 3,
        name: '50 Cent - P.I.M.P',
        singer: 'NethMG Remix',
        path: './assets/music/song3.mp3',
        image: './assets/img/song3.jpg',
    },
    {
        id: 4,
        name: 'LALALA Remix',
        singer: 'Gin ft VK',
        path: './assets/music/song4.mp3',
        image: './assets/img/song4.jpg',
    },
    {
        id: 5,
        name: 'Nắng Ấm Xa Dần',
        singer: 'Sơn Tùng M-TP',
        path: './assets/music/song5.mp3',
        image: './assets/img/song5.png',
    },
    {
        id: 6,
        name: 'Low (Remix 2021)',
        singer: 'Flo Rida & T-Pain',
        path: './assets/music/song6.mp3',
        image: './assets/img/song6.png',
    },
    {
        id: 7,
        name: 'Sứ Thanh Hoa Remix',
        singer: 'Phong Max Remix',
        path: './assets/music/song7.mp3',
        image: './assets/img/song7.png',
    },
    {
        id: 8,
        name: 'Move Your Body Remix 2021',
        singer: 'DJ Topeng ft. Sia',
        path: './assets/music/song8.mp3',
        image: './assets/img/song8.jpg',
    },
    {
        id: 9,
        name: 'This Is What You Came For',
        singer: 'Calvin Harris ft. Rihanna',
        path: './assets/music/song9.mp3',
        image: './assets/img/song9.jpg',
    },
    {
        id: 10,
        name: 'Xích Linh Remix',
        singer: 'Calvin Harris ft. Rihanna',
        path: './assets/music/song10.mp3',
        image: './assets/img/song10.png',
    },
    {
        id: 11,
        name: 'Khúc Cửu Môn Hồi Ức',
        singer: 'Đẳng Thập Ma Quân',
        path: './assets/music/song11.mp3',
        image: './assets/img/song11.jpg',
    },
    {
        id: 12,
        name: 'Lake Arrowhead',
        singer: 'Nora En Pure',
        path: './assets/music/song12.mp3',
        image: './assets/img/song12.jpg',
    },
    {
        id: 13,
        name: 'Power',
        singer: 'Interupt & Luna LePage',
        path: './assets/music/song13.mp3',
        image: './assets/img/song13.gif',
    },
];
